apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline-lab
  namespace: public-apps
spec:
  chart:
    spec:
      chart: pipeline-lab
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: visegue-public
  interval: 10m0s
  values:
    affinity: {}
    autoscaling:
      enabled: false
      maxReplicas: 3
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
    fullnameOverride: ""
    image:
      pullPolicy: IfNotPresent
      repository: harbor.visegue.se/visegue-public
    imagePullSecrets: []
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.allow-http: "false"
        kubernetes.io/ingress.class: nginx
      enabled: true
      hosts:
      - host: pipeline-labs.visegue.se
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
      - hosts:
        - pipeline-labs.visegue.se
        secretName: pipeline-labs-tls
    livenessProbe:
      httpGet:
        path: /
        port: http
    nameOverride: ""
    nodeSelector: {}
    podAnnotations: {}
    podSecurityContext: {}
    ports:
    - containerPort: 3000
      name: http
      protocol: TCP
    readinessProbe:
      httpGet:
        path: /
        port: http
    replicaCount: 1
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext: {}
    service:
      port: 80
      type: ClusterIP
    serviceAccount:
      annotations: {}
      create: true
      name: ""
    tolerations: []